# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Llf750LIO4cF7cK16b4gobActebD2--p
"""

import pandas as pd

df=pd.read_csv("/content/cardekho_dataset.csv")

df.head()

df.info()

df.isnull().sum()

df.describe()

df[df['seats']==0]

df=df[df['seats']!=0]

df.sort_values('km_driven',ascending=False).head(25)

df[df["km_driven"]==df["selling_price"]].sort_values('selling_price',ascending=False)

df['brand'].unique()

df['brand']=df['brand'].str.lower()

df.shape

df=df[df['km_driven']<=950000]

counts=df['brand'].value_counts()

rare_cars=counts[counts<10]
print(rare_cars)

x=df[~df['brand'].isin(rare_cars.index)]
x['brand'].value_counts()
df=x

df.columns

feature=['brand','model','vehicle_age','km_driven','seller_type','fuel_type','transmission_type','mileage','engine','max_power','seats']

X=df[feature]
y=df['selling_price']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)
print(X_train.shape, X_test.shape)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error

lr=LinearRegression()
lr.fit(X_train,y_train)

pred=lr.predict(X_test)

print(r2_score(y_test,pred),mean_absolute_error(y_test,pred))

from sklearn.ensemble import RandomForestRegressor

rf=RandomForestRegressor(n_estimators=100,random_state=34,n_jobs=-1)
rf.fit(X_train,y_train)
rf_pred=rf.predict(X_test)
print(r2_score(y_test, rf_pred), mean_absolute_error(y_test, rf_pred))

rf_train=rf.predict(X_train)
print(r2_score(y_train,rf_train))

for d in [3, 5, 8, 12, 20]:
    m = RandomForestRegressor(n_estimators=100, max_depth=d, random_state=5, n_jobs=-1)
    m.fit(X_train, y_train)
    print(d, round(r2_score(y_train, m.predict(X_train)), 3), round(r2_score(y_test, m.predict(X_test)), 3))

import numpy as np
y_train_log=np.log(y_train)

n_rf=RandomForestRegressor(n_estimators=100,random_state=5,n_jobs=-1)
n_rf.fit(X_train,y_train_log)
pred_ict=n_rf.predict(X_test)
pred_ict_back=np.exp(pred_ict)

print(r2_score(y_test,pred_ict_back),mean_absolute_error(y_test,pred_ict_back))

check = X_test.copy()
check['actual'] = y_test
check['pred'] = rf_pred
check['error'] = (check['actual'] - check['pred']).abs()
check.sort_values('error', ascending=False).head(10)

print(df.shape)
print(X.shape)
print(X_train.shape)

X_all=pd.get_dummies(X)
print(X_all.shape)

from sklearn.model_selection import cross_validate
cv_model=RandomForestRegressor(n_estimators=100,random_state=34,n_jobs=-1)
scores=cross_validate(cv_model,X_all,y,cv=5,scoring=['r2','neg_mean_absolute_error'])

print("R2:",scores['test_r2'])
print("MAE:",scores['test_neg_mean_absolute_error'])

r2 = scores['test_r2']
mae = -scores['test_neg_mean_absolute_error']

print("R2 per fold :", r2)
print("Average R2  :", r2.mean())
print("MAE per fold:", mae)
print("Average MAE :", mae.mean())

important=pd.Series(rf.feature_importances_,index=X_train.columns)
important.sort_values(ascending=False).head(15)